# Generated by Django 3.2.7 on 2021-09-12 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_education_skillset_summarysection_workexperience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summarysection',
            name='picture',
        ),
    ]
